name: CI

on:
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        zig: [0.16.0]
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    name: Zig ${{ matrix.zig }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Zig
        uses: mlugg/setup-zig@v2
        with:
          zig-version: ${{ matrix.zig }}
      - run: zig build test
